## A script to make the metadata.csv file located in inst/extdata of
## the package.See ?AnnotationHubData::makeAnnotationHubMetadata for a
## description of the metadata.csv file, expected fields and data
## types. This AnnotationHubData::makeAnnotationHubMetadata() function
## can be used to validate the metadata.csv file before submitting the
## package.

metadata <-
    data.frame(
        Title = c(
            "ko15.CDF",
            "cptac_a_b_c_peptides.txt",
            "cptac_a_b_peptides.txt",
            "cptac_peptides.txt",
            "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid",
            "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz",
            "20171016_POOL_POS_1_105-134.mzML",
            "20171016_POOL_POS_3_105-134.mzML",
            "PestMix1_DDA.mzML",
            "PestMix1_SWATH.mzML",
            "benchmarkingDIA.tsv",
            "Report-Derks2022-plexDIA.tsv",
            "Ai2025_aCMs_report.tsv",
            "Ai2025_iCMs_report.tsv",
            "crap_gpm.fasta",
            "crap_ccp.fasta",
            "crap_maxquant.fasta.gz",
            "CEMS_10ppm.mzML",
            "CEMS_25ppm.mzML",
            "HAM004_641fE_14-11-07--Exp1.extracted.mzML",
            "HAM004_641fE_14-11-07--Exp2.extracted.mzML",
            "HAM004_641fE_14-11-07--Exp3.extracted.mzML",
            "HAM004_641fE_14-11-07--Exp4.extracted.mzML",
            "HAM004_641fE_14-11-07--Exp5.extracted.mzML",
            "HAM005_641fE_14-11-07--Exp1.extracted.mzML",
            "HAM005_641fE_14-11-07--Exp2.extracted.mzML",
            "HAM005_641fE_14-11-07--Exp3.extracted.mzML",
            "HAM005_641fE_14-11-07--Exp4.extracted.mzML",
            "HAM005_641fE_14-11-07--Exp5.extracted.mzML",
            "MRM-standmix-5.mzML",
            "MS3TMT11.mzML",
            "MS3TMT10_01022016_32917-33481.mzML.gz",
            "fdms3tmt11.rda",
            "D19_15um30cm_SC1.mzML",
            "OR11_20160122_PG_HeLa_CVB3_CT_A.mzML",
            "D19_15um30cm_SC1.sage.tsv",
            "OR11_20160122_PG_HeLa_CVB3_CT_A.sage.tsv"
        ),
        Description = c(
            "Raw metabolomics MS file in netCDF format. See ?ko15.CDF for details.",
            "Conditions A, B and C of the CPTAC quantitative proteomics data (tab-delimited format). See ?cptac for details.",
            "Conditions A and B of the CPTAC quantitative proteomics data (tab-delimited format). See ?cptac for details.",
            "CPTAC quantitative proteomics data (tab-delimited format). See ?cptac for details.",
            "Peptide spectrum matches from the PDX000001 experiment. See ?PXD000001 for details.",
            "Raw MS data from the PDX000001 experiment, in mzML format. See ?PXD000001 for details.",
            "AB Sciex LC-MS data file (injection index 1), in mzML format. See ?sciex for details.",
            "AB Sciex LC-MS data file (injection index 19), in mzML format. See ?sciex for details.",
            "Triple TOF DDA raw data, in mzML format. See ?TripleTOF for details.",
            "Triple TOF SWATH raw data, in mzML format. See ?TripleTOF for details.",
            "Output of DIA-NN software (report.tsv)",
            "Derk et al. (2022) single-cell proteomics plexDIA results (DIA-NN report.tsv).",
            "Ai et al. (2025) Single Cell Proteomics Reveals Specific Cellular Subtypes in Cardiomyocytes Derived from Human iPSCs and Adult Hearts.",
            "Ai et al. (2025) Single Cell Proteomics Reveals Specific Cellular Subtypes in Cardiomyocytes Derived from Human iPSCs and Adult Hearts.",
            "common Repository of Adventitious Proteins (cRAP) from the Global Proteome Machine (GPM)",
            "common Repository of Adventitious Proteins (cRAP) from the Cambridge Centre for Proteomics (CCP)",
            "MaxQuant's contaminant database",
            "CE-MS data file (10ppm), in mzML format. See ?CEMS for details.",
            "CE-MS data file (25ppm) in mzML format. See ?CEMS for details.",
            "FTICR-MS data file HAM4, experiment 1, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM4, experiment 2, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM4, experiment 3, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM4, experiment 4, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM4, experiment 5, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM5, experiment 1, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM5, experiment 2, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM5, experiment 3, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM5, experiment 4, in mzML file. See ?FTICR for details",
            "FTICR-MS data file HAM5, experiment 5, in mzML file. See ?FTICR for details",
            "Multiple Reaction Monitoring mode (MRM) file from a mouse brain sample. See ?MRM fo details",
            "A subset of 994 spectra from a currenly unpublished MS3 SPS TMT 11-plex experiment",
            "A subset of 565 spectra from a currenly unpublished MS3 SPS TMT 10-plex experiment",
            "Feature data of the MS3TMT11 data",
            "Boekweg et al. (2022) SCP mzML file. See ?Boekweg2022 for details.",
            "Boekweg et al. (2022) bulk mzML file. See ?Boekweg2022 for details.",
            "Boekweg et al. (2022) Sage PSMs for D19_15um30cm_SC1. See ?Boekweg2022 for details.",
            "Boekweg et al. (2022) Sage PSMs for OR11_20160122_PG_HeLa_CVB3_CT_A. See ?Boekweg2022 for details."
        ),
        BiocVersion = c(
            rep("3.17", 11),
            "3.19",
            "3.21",
            "3.21",
            "3.21",
            "3.21",
            "3.21",
            "3.23",
            "3.23",
            rep("3.23", 10),
            "3.23",
            rep("3.23", 3),
            rep("3.23", 4)
        ),
        Genome = "",
        SourceType = c(
            "CDF",
            "TXT",
            "TXT",
            "TXT",
            "mzid",
            "mzML",
            "mzML",
            "mzML",
            "mzML",
            "mzML",
            "TSV",
            "TSV",
            "TSV",
            "TSV",
            "FASTA",
            "FASTA",
            "FASTA",
            "mzML",
            "mzML",
            rep("mzML", 10),
            "mzML",
            "mzML",
            "mzML",
            "RDA",
            "mzML",
            "mzML",
            "TSV",
            "TSV"
        ),
        SourceUrl = c(
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://uclouvain-cbio.github.io/WSBIM2122/data/cptac_a_b_c_peptides.txt",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://raw.githubusercontent.com/statOmics/PDA/data/quantification/fullCptacDatasSetNotForTutorial/peptides.txt",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://ftp.pride.ebi.ac.uk/pride/data/archive/2012/03/PXD000001/",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://bioconductor.org/packages/3.16/data/experiment/html/msdata.html",
            "https://zenodo.org/records/8063173",
            "https://drive.google.com/drive/folders/1pUC2zgXKtKYn22mlor0lmUDK0frgwL_-",
            "ftp://massive.ucsd.edu/v07/MSV000094438/updates/2024-10-23_bineka_5deafa61/other/Supplementary%20Files/aCMs/report.tsv",
            "ftp://massive.ucsd.edu/v07/MSV000094438/updates/2024-10-23_bineka_5deafa61/other/Supplementary%20Files/iCMs/report1.tsv",
            "https://zenodo.org/records/15115102/files/crap_gpm.fasta",
            "https://zenodo.org/records/15115102/files/crap_ccp.fasta",
            "https://zenodo.org/records/15115102/files/crap_maxquant.fasta.gz",
            "https://zenodo.org/records/18481720/files/CEMS_10ppm.mzML",
            "https://zenodo.org/records/18481720/files/CEMS_25ppm.mzML",
            "https://zenodo.org/records/18494294/files/HAM004_641fE_14-11-07--Exp1.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM004_641fE_14-11-07--Exp2.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM004_641fE_14-11-07--Exp3.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM004_641fE_14-11-07--Exp4.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM004_641fE_14-11-07--Exp5.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM005_641fE_14-11-07--Exp1.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM005_641fE_14-11-07--Exp2.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM005_641fE_14-11-07--Exp3.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM005_641fE_14-11-07--Exp4.extracted.mzML",
            "https://zenodo.org/records/18494294/files/HAM005_641fE_14-11-07--Exp5.extracted.mzML",
            "https://zenodo.org/records/18502866/files/MRM-standmix-5.mzML",
            "https://zenodo.org/records/19127509/files/MS3TMT11.mzML",
            "https://zenodo.org/records/19127509/files/MS3TMT10_01022016_32917-33481.mzML.gz",
            "https://zenodo.org/records/19127509/files/fdms3tmt11.rda",
            "ftp://massive-ftp.ucsd.edu/v03/MSV000087524/updates/2021-11-01_hboekweg_5ab97297/raw/D19_15um30cm_SC1.mzML",
            "ftp://massive-ftp.ucsd.edu/v03/MSV000087689/ccms_peak/Hela_bulk/OR11_20160122_PG_HeLa_CVB3_CT_A.mzML",
            "https://zenodo.org/records/19370231/files/D19_15um30cm_SC1.sage.tsv",
            "https://zenodo.org/records/19370231/files/OR11_20160122_PG_HeLa_CVB3_CT_A.sage.tsv"
        ),
        SourceVersion = rep("1.0", 37),
        Species = c(
            "Mus musculus",
            "Saccharomyces cerevisiae",
            "Saccharomyces cerevisiae",
            "Saccharomyces cerevisiae",
            "Erwinia carotovora",
            "Erwinia carotovora",
            "Homo sapiens",
            "Homo sapiens",
            "",
            "",
            "Homo sapiens",
            "Homo sapiens",
            "Homo sapiens",
            "Homo sapiens",
            "",
            "",
            "",
            "",
            "",
            rep("", 10),
            "Mus musculus",
            rep("", 3),
            rep("Homo sapiens", 4)
        ),
        TaxonomyId = c(
            "10090",
            "4932",
            "4932",
            "4932",
            "554",
            "554",
            "9606",
            "9606",
            "",
            "",
            "9606",
            "9606",
            "9606",
            "9606",
            "",
            "",
            "",
            "",
            "",
            rep("", 10),
            "10090",
            rep("", 3),
            rep("9606", 4)
        ),
        Coordinate_1_based = "",
        DataProvider = "",
        Maintainer = "Laurent Gatto <laurent.gatto@uclouvain.be>",
        RDataClass = c(
            "Spectra",
            "data.frame",
            "data.frame",
            "data.frame",
            "Spectra",
            "PSM",
            "Spectra",
            "Spectra",
            "Spectra",
            "Spectra",
            "data.frame",
            "data.frame",
            "data.frame",
            "data.frame",
            "AAStringSet",
            "AAStringSet",
            "AAStringSet",
            "Spectra",
            "Spectra",
            rep("Spectra", 10),
            "Spectra",
            "Spectra",
            "Spectra",
            "data.frame",
            "Spectra",
            "Spectra",
            "data.frame",
            "data.frame"
        ),
        DispatchClass = c(
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            "FilePath",
            rep("FilePath", 10),
            "FilePath",
            rep("FilePath", 3),
            rep("FilePath", 4)
        ),
        ## NB: locally, the data are stored in the package's data directory, but
        ## in the Azure cloud, they are located in the package's root directory.
        Location_Prefix = c(
            rep("", times = 10),
            "https://zenodo.org/",
            "https://zenodo.org/",
            "ftp://massive.ucsd.edu/",
            "ftp://massive.ucsd.edu/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "https://zenodo.org/",
            "ftp://massive-ftp.ucsd.edu/",
            "ftp://massive-ftp.ucsd.edu/",
            "https://zenodo.org/",
            "https://zenodo.org/"
        ),
        RDataPath = c(
            "MsDataHub/cdf/ko15.CDF",
            "MsDataHub/cptac/cptac_a_b_c_peptides.txt",
            "MsDataHub/cptac/cptac_a_b_peptides.txt",
            "MsDataHub/cptac/cptac_peptides.txt",
            "MsDataHub/PXD000001/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid",
            "MsDataHub/PXD000001/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML.gz",
            "MsDataHub/sciex/20171016_POOL_POS_1_105-134.mzML",
            "MsDataHub/sciex/20171016_POOL_POS_3_105-134.mzML",
            "MsDataHub/TripleTOF-SWATH/PestMix1_DDA.mzML",
            "MsDataHub/TripleTOF-SWATH/PestMix1_SWATH.mzML",
            "record/8063173/files/benchmarkingDIA.tsv",
            "records/10938597/files/Report-Derks2022-plexDIA.tsv",
            "v07/MSV000094438/updates/2024-10-23_bineka_5deafa61/other/Supplementary%20Files/aCMs/report.tsv",
            "v07/MSV000094438/updates/2024-10-23_bineka_5deafa61/other/Supplementary%20Files/iCMs/report1.tsv",
            "records/15115102/files/crap_gpm.fasta",
            "records/15115102/files/crap_ccp.fasta",
            "records/15115102/files/crap_maxquant.fasta.gz",
            "records/18481720/files/CEMS_10ppm.mzML",
            "records/18481720/files/CEMS_25ppm.mzML",
            "records/18494294/files/HAM004_641fE_14-11-07--Exp1.extracted.mzML",
            "records/18494294/files/HAM004_641fE_14-11-07--Exp2.extracted.mzML",
            "records/18494294/files/HAM004_641fE_14-11-07--Exp3.extracted.mzML",
            "records/18494294/files/HAM004_641fE_14-11-07--Exp4.extracted.mzML",
            "records/18494294/files/HAM004_641fE_14-11-07--Exp5.extracted.mzML",
            "records/18494294/files/HAM005_641fE_14-11-07--Exp1.extracted.mzML",
            "records/18494294/files/HAM005_641fE_14-11-07--Exp2.extracted.mzML",
            "records/18494294/files/HAM005_641fE_14-11-07--Exp3.extracted.mzML",
            "records/18494294/files/HAM005_641fE_14-11-07--Exp4.extracted.mzML",
            "records/18494294/files/HAM005_641fE_14-11-07--Exp5.extracted.mzML",
            "records/18502866/files/MRM-standmix-5.mzML",
            "records/19127509/files/MS3TMT11.mzML",
            "records/19127509/files/MS3TMT10_01022016_32917-33481.mzML.gz",
            "records/19127509/files/fdms3tmt11.rda",
            "v03/MSV000087524/updates/2021-11-01_hboekweg_5ab97297/raw/D19_15um30cm_SC1.mzML",
            "v03/MSV000087689/ccms_peak/Hela_bulk/OR11_20160122_PG_HeLa_CVB3_CT_A.mzML",
            "records/19370231/files/D19_15um30cm_SC1.tsv",
            "records/19370231/files/OR11_20160122_PG_HeLa_CVB3_CT_A.tsv"
        ),
        Tags = ""
    )


## Metadata for MS-based DDA and DIA datasets for the MsDataHub package files
## (https://zenodo.org/records/19137577).

miscDdaDiaData <-
    data.frame(
    Title = c(
        "Christoforou_2016_TMT_DDA_FragPipe_Fraction1_psm.tsv",
        "Christoforou_2016_TMT_DDA_FragPipe_Fraction2_psm.tsv",
        "Christoforou_2016_TMT_DDA_MaxQuant_evidence.txt",
        "Christoforou_2016_TMT_DDA_sage_results.sage.tsv",
        "Christoforou_2016_TMT_DDA_sage_tmt.tsv",
        "Derks_2022_plex_DIA_DIANN_report-subset.tsv",
        "Derks_2022_plex_DIA_DIANN_report_subset.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_A_1_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_A_2_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_A_3_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_B_1_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_B_2_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_FragPipe_B_3_psm.tsv",
        "vanPuyvelde_2022_LFQ_DDA_MaxQuant_evidence.txt",
        "vanPuyvelde_2022_LFQ_DDA_MaxQuant_peptides.txt",
        "vanPuyvelde_2022_LFQ_DDA_MaxQuant_proteinGroups.txt",
        "vanPuyvelde_2022_LFQ_DDA_PEAKS_LFQ_report.csv",
        "vanPuyvelde_2022_LFQ_DDA_sage_lfq.tsv",
        "vanPuyvelde_2022_LFQ_DDA_sage_results.sage.tsv",
        "vanPuyvelde_2022_LFQ_DIA_DIANN_report.parquet",
        "vanPuyvelde_2022_LFQ_DIA_DIANN_report.tsv"),
    Description = "Various DDA and DIA files to illustrate QFeatures::readQFeatures()",
    BiocVersion = "3.23",
    Genome = "",
    SourceType = c("TSV", "TSV", "TXT", "TSV", "TSV", "TSV", "TSV", "TSV",
                   "TSV", "TSV", "TSV", "TSV", "TSV", "TXT", "TXT", "TXT",
                   "CSV", "YSV", "TSV", "Parquet", "TSV"),
    SourceUrl = c(
        "https://zenodo.org/records/19137577/files/Christoforou_2016_TMT_DDA_FragPipe_Fraction1_psm.tsv",
        "https://zenodo.org/records/19137577/files/Christoforou_2016_TMT_DDA_FragPipe_Fraction2_psm.tsv",
        "https://zenodo.org/records/19137577/files/Christoforou_2016_TMT_DDA_MaxQuant_evidence.txt",
        "https://zenodo.org/records/19137577/files/Christoforou_2016_TMT_DDA_sage_results.sage.tsv",
        "https://zenodo.org/records/19137577/files/Christoforou_2016_TMT_DDA_sage_tmt.tsv",
        "https://zenodo.org/records/19137577/files/Derks_2022_plex_DIA_DIANN_report-subset.tsv",
        "https://zenodo.org/records/19137577/files/Derks_2022_plex_DIA_DIANN_report_subset.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_1_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_2_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_3_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_1_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_2_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_3_psm.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_evidence.txt",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_peptides.txt",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_proteinGroups.txt",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_PEAKS_LFQ_report.csv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_sage_lfq.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DDA_sage_results.sage.tsv",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DIA_DIANN_report.parquet",
        "https://zenodo.org/records/19137577/files/vanPuyvelde_2022_LFQ_DIA_DIANN_report.tsv"),
    SourceVersion = "1.0",
    Species = c(
        rep("Mus musculus", 5), ## Christoforou (2016)
        rep(NA, 2),   ## Derks (2022) - mixed species
        rep(NA, 14)), ## vanPuyvelde (2022) - mixed species
    TaxonomyId = c(
        rep("10090", 5),
        rep("", 2 + 14)),
    Coordinate_1_based = "",
    DataProvider = "",
    Maintainer = "Laurent Gatto <laurent.gatto@uclouvain.be>",
    RDataClass = "data.frame",
    DispatchClass = "FilePath",
    Location_Prefix = "https://zenodo.org/",
    RDataPath = c(
        "records/19137577/files/Christoforou_2016_TMT_DDA_FragPipe_Fraction1_psm.tsv",
        "records/19137577/files/Christoforou_2016_TMT_DDA_FragPipe_Fraction2_psm.tsv",
        "records/19137577/files/Christoforou_2016_TMT_DDA_MaxQuant_evidence.txt",
        "records/19137577/files/Christoforou_2016_TMT_DDA_sage_results.sage.tsv",
        "records/19137577/files/Christoforou_2016_TMT_DDA_sage_tmt.tsv",
        "records/19137577/files/Derks_2022_plex_DIA_DIANN_report-subset.tsv",
        "records/19137577/files/Derks_2022_plex_DIA_DIANN_report_subset.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_1_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_2_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_A_3_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_1_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_2_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_FragPipe_B_3_psm.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_evidence.txt",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_peptides.txt",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_MaxQuant_proteinGroups.txt",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_PEAKS_LFQ_report.csv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_sage_lfq.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DDA_sage_results.sage.tsv",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DIA_DIANN_report.parquet",
        "records/19137577/files/vanPuyvelde_2022_LFQ_DIA_DIANN_report.tsv"),
    Tags = "")


metadata <- rbind(metadata, miscDdaDiaData)


## The experiment titles are conferted into functions to directly
## access the individual resources. This requires that they correspond
## to valid unique symbol names. To assert this, then are converted
## with make.names().
metadata[["Title"]] <- make.names(metadata[["Title"]])


if (!grepl("MsDataHub/inst/scripts", getwd())) {
    stop("Run from MsDataHub/inst/scripts")
}

library(here)
write.csv(metadata,
    file = here("inst", "extdata", "metadata.csv"),
    row.names = FALSE
)

# pkg_source <- file.path(ifelse(file.exists("~/wrk"), "~/wrk", "~/dev"),
#                         "MsDataHub")

pkg_source <- file.path(
    ifelse(file.exists("~/dev"), "~/dev", "~/wrk"),
    "MsDataHub"
)
pkg_source <- here()
stopifnot(file.exists(pkg_source))

AnnotationHubData::makeAnnotationHubMetadata(
    pathToPackage = pkg_source,
    fileName = "metadata.csv"
)
